/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AjanlatainkRouteImport } from './routes/ajanlataink'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HusegprogramRouteImport } from './routes/husegprogram'
import { Route as MenunkRouteImport } from './routes/menunk'
import { Route as NyeremenyjatekRouteImport } from './routes/nyeremenyjatek'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TePizzadRouteImport } from './routes/te-pizzad'
import { Route as MarkakBrandRouteImport } from './routes/markak.$brand'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ApiPublicShopifyOrderRouteImport } from './routes/api/public/shopify-order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AjanlatainkRoute = AjanlatainkRouteImport.update({
  id: '/ajanlataink',
  path: '/ajanlataink',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HusegprogramRoute = HusegprogramRouteImport.update({
  id: '/husegprogram',
  path: '/husegprogram',
  getParentRoute: () => rootRouteImport,
} as any)
const MenunkRoute = MenunkRouteImport.update({
  id: '/menunk',
  path: '/menunk',
  getParentRoute: () => rootRouteImport,
} as any)
const NyeremenyjatekRoute = NyeremenyjatekRouteImport.update({
  id: '/nyeremenyjatek',
  path: '/nyeremenyjatek',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TePizzadRoute = TePizzadRouteImport.update({
  id: '/te-pizzad',
  path: '/te-pizzad',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkakBrandRoute = MarkakBrandRouteImport.update({
  id: '/markak/$brand',
  path: '/markak/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyOrderRoute = ApiPublicShopifyOrderRouteImport.update({
  id: '/api/public/shopify-order',
  path: '/api/public/shopify-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ajanlataink': typeof AjanlatainkRoute
  '/contact': typeof ContactRoute
  '/husegprogram': typeof HusegprogramRoute
  '/menunk': typeof MenunkRoute
  '/nyeremenyjatek': typeof NyeremenyjatekRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/te-pizzad': typeof TePizzadRoute
  '/markak/$brand': typeof MarkakBrandRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/shopify-order': typeof ApiPublicShopifyOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ajanlataink': typeof AjanlatainkRoute
  '/contact': typeof ContactRoute
  '/husegprogram': typeof HusegprogramRoute
  '/menunk': typeof MenunkRoute
  '/nyeremenyjatek': typeof NyeremenyjatekRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/te-pizzad': typeof TePizzadRoute
  '/markak/$brand': typeof MarkakBrandRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/shopify-order': typeof ApiPublicShopifyOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ajanlataink': typeof AjanlatainkRoute
  '/contact': typeof ContactRoute
  '/husegprogram': typeof HusegprogramRoute
  '/menunk': typeof MenunkRoute
  '/nyeremenyjatek': typeof NyeremenyjatekRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/te-pizzad': typeof TePizzadRoute
  '/markak/$brand': typeof MarkakBrandRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/shopify-order': typeof ApiPublicShopifyOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ajanlataink'
    | '/contact'
    | '/husegprogram'
    | '/menunk'
    | '/nyeremenyjatek'
    | '/sitemap.xml'
    | '/te-pizzad'
    | '/markak/$brand'
    | '/product/$handle'
    | '/api/public/shopify-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ajanlataink'
    | '/contact'
    | '/husegprogram'
    | '/menunk'
    | '/nyeremenyjatek'
    | '/sitemap.xml'
    | '/te-pizzad'
    | '/markak/$brand'
    | '/product/$handle'
    | '/api/public/shopify-order'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ajanlataink'
    | '/contact'
    | '/husegprogram'
    | '/menunk'
    | '/nyeremenyjatek'
    | '/sitemap.xml'
    | '/te-pizzad'
    | '/markak/$brand'
    | '/product/$handle'
    | '/api/public/shopify-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AjanlatainkRoute: typeof AjanlatainkRoute
  ContactRoute: typeof ContactRoute
  HusegprogramRoute: typeof HusegprogramRoute
  MenunkRoute: typeof MenunkRoute
  NyeremenyjatekRoute: typeof NyeremenyjatekRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TePizzadRoute: typeof TePizzadRoute
  MarkakBrandRoute: typeof MarkakBrandRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ApiPublicShopifyOrderRoute: typeof ApiPublicShopifyOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajanlataink': {
      id: '/ajanlataink'
      path: '/ajanlataink'
      fullPath: '/ajanlataink'
      preLoaderRoute: typeof AjanlatainkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husegprogram': {
      id: '/husegprogram'
      path: '/husegprogram'
      fullPath: '/husegprogram'
      preLoaderRoute: typeof HusegprogramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menunk': {
      id: '/menunk'
      path: '/menunk'
      fullPath: '/menunk'
      preLoaderRoute: typeof MenunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyeremenyjatek': {
      id: '/nyeremenyjatek'
      path: '/nyeremenyjatek'
      fullPath: '/nyeremenyjatek'
      preLoaderRoute: typeof NyeremenyjatekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/te-pizzad': {
      id: '/te-pizzad'
      path: '/te-pizzad'
      fullPath: '/te-pizzad'
      preLoaderRoute: typeof TePizzadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markak/$brand': {
      id: '/markak/$brand'
      path: '/markak/$brand'
      fullPath: '/markak/$brand'
      preLoaderRoute: typeof MarkakBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify-order': {
      id: '/api/public/shopify-order'
      path: '/api/public/shopify-order'
      fullPath: '/api/public/shopify-order'
      preLoaderRoute: typeof ApiPublicShopifyOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AjanlatainkRoute: AjanlatainkRoute,
  ContactRoute: ContactRoute,
  HusegprogramRoute: HusegprogramRoute,
  MenunkRoute: MenunkRoute,
  NyeremenyjatekRoute: NyeremenyjatekRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TePizzadRoute: TePizzadRoute,
  MarkakBrandRoute: MarkakBrandRoute,
  ProductHandleRoute: ProductHandleRoute,
  ApiPublicShopifyOrderRoute: ApiPublicShopifyOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
